run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - deadcode
    - dogsled
    - errcheck
    - goconst
    - gocyclo
    - goimports
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck

linters-settings:
  dogsled:
    max-blank-identifiers: 2
  errcheck:
    check-type-assertions: true
    check-blank: true
  gocyclo:
    min-complexity: 10
  govet:
    check-shadowing: true
  lll:
    line-length: 100
  misspell:
    locale: US

issues:
  exclude-rules:
    - linters:
        - lll
      source: "^//go:generate "
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  new: true
